services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - db-data:/pb/pb_data

volumes:
  db-data: